# Generated by Django 4.0.3 on 2022-03-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datapoints', to='label_mgt.category'),
        ),
    ]
